### ISSUE TITLE
Issue with job submission

### ISSUE THREAD

**Issue by somnathtagore** [epigen/scifiRNA-seq#5] opened 2020-11-20 14:55 UTC
Hi, 
I am running the scifi exe file on cluster as a job, and am passing the configuration file at runtime using -c. It is throwing the following error.

scifi:pipeline:L112 (main) [INFO] > scifi-RNA-seq pipeline
scifi:pipeline:L137 (main) [INFO] > Samples to submit:
         - scifi_L001
         - scifi_L002
         - scifi_L003
         - scifi_L004
Traceback (most recent call last):
  File "/.../anaconda3/envs/my_pymc_env/bin/scifi", line 11, in <module>
    load_entry_point('scifi', 'console_scripts', 'scifi')()
  File "/.../anaconda3/envs/my_pymc_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/.../anaconda3/envs/my_pymc_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/.../anaconda3/envs/my_pymc_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/.../anaconda3/envs/my_pymc_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/.../scifiRNA-seq/build/lib/scifi/__init__.py", line 171, in <module>
    sys.exit(main())
  File "/.../scifiRNA-seq/build/lib/scifi/pipeline.py", line 152, in main
    map_command(args, sample_name, sample_out_dir, r1_annotation, _CONFIG)
  File "/.../scifiRNA-seq/build/lib/scifi/map.py", line 85, in map_command
    submit_job(job, params)
  File "/.../scifiRNA-seq/build/lib/scifi/job_control.py", line 41, in submit_job
    array="" if array is not None else "", **params
KeyError: 'job_name'

Please let me know what the issue is.

Thanks!
Som

**Comment by afrendeiro** [comment] 2020-11-20 16:39
Duplicate of #3

**Closed as completed** 2020-11-20 16:41 UTC
